FROM node:20-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    make

WORKDIR /app

COPY ui ./ui
COPY make ./make
COPY makefile .

# Install dependencies
WORKDIR /app/ui
RUN npm ci

WORKDIR /app
RUN touch .env

# Expose port 3000
EXPOSE 3000

# Run development server
CMD ["sh", "-c", "make run_ui"]