FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# Ref : https://docs.astral.sh/uv/guides/integration/docker/

# Install make and other build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    make \
    && rm -rf /var/lib/apt/lists/*

# Copy project to docker 
COPY config /config
COPY app /app
COPY make ./make

COPY uv.lock .
COPY pyproject.toml .
COPY makefile .

RUN touch .env

EXPOSE 8000

RUN make install

# Default command
CMD ["sh", "-c", "make celery-worker"]